server:
  port: 8585
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankapp
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 465
    username: ${email_id}
    password: ${email_password}
    properties:
      mail:
        debug: false
        protocol: smtp
        smtp:
          ssl:
            enable: true
            trust: "*"
          auth: true
          starttls:
            enable: true
            required: false

app:
  jwt-secret: 2CFBCF181AC46BED9FAB14C7FB7F9AC46BED9FAB14C7FB7F
  jwt-expiration: 86400000