spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "3.0"
cards:
  message: "Welcome to MyBank cards related prod APIs"
  contactDetails:
    name: "Reine Ray - Product Owner"
    email: "reineay@eazybank.com"
  onCallSupport:
    - (444) 555-1234
    - (444) 523-1345